### ISSUE TITLE
Local variables

### ISSUE THREAD

**Issue by davepagurek** [calder-gl/calder#27]
`Variable` represents a name-kind pair. A `Variable` can either come from somewhere in the program or from an external source. Right now we have `Interface` as one source. To add local variables, I propose we abstract `Interface` into `VariableSource`:

```typescript
interface VariableSource extends Hashable {
  variable: Variable;
  source(): string;
}

class Interface implements VariableSource { ... }
class Local implements VariableSource { ... }
```

**Comment by davepagurek** [comment]
Things to think about: How do we compute dependencies? Maybe we add `dependencies()` to the interface, and a local variable just has none? That was a `Reference` to can just call `dependencies()` on its `VariableSource` member

**Comment by abhimadan** [comment]
I was under the impression that variables have no dependencies. Unless you mean that, when computing `SyntaxNode` dependencies, we only use `InterfaceVariable`s so that we can declare them at the top of the shader source? 

Alternatively, we add a `DeclareVariable` syntax node, so that we don't use dependencies to generate declarations. We can assume that programs are reasonably well-formed (i.e. no declare-after-use).

**Comment by davepagurek** [comment]
Right, variables have no dependencies. I'm trying to think of a way to give `Reference` the information of whether or not it has an `InterfaceVariable` (in which case, the `Reference` has a dependency) or a `LocalVariable` (in which case, it doesn't have one) without actually switching on the type. If the interface they both conform to (and not their internal `Variable` member) has a `dependencies()` method, then that would be one way to give the `Reference` the info it needs

**Comment by abhimadan** [comment]
From the current code, it looks like we only use dependencies to determine which interface variables to declare at the top. Couldn't we solve this problem by adding declaration nodes? We can add a separate one for interface variables (`DeclareInterfaceVariable`) and one for local variables (`DeclareLocalVariable`).

**Comment by davepagurek** [comment]
We could, but I feel like assuming the code is well-formed and declares everything that gets used partially defeats the purpose of using a tool like this. Maybe that's a problem to address later, though.

**Comment by abhimadan** [comment]
I agree, but I don't think that's a problem we can address at the current time. Or at least, I don't think it's a problem we can solve as the AST is being constructed. We would need an additional pass to check scoping and declare-before-use. That's why I think it's fine to assume it works for now, and catch the errors once we add shader compilation.

**Comment by davepagurek** [comment]
If we're doing that, we can maybe take out the `dependencies()` thing in general

**Comment by abhimadan** [comment]
Yeah agreed
